### ISSUE TITLE
Implement hash checking using blake3

### ISSUE THREAD

**Issue by pwnwriter** [pwnwriter/hysp#3]
Without hash verifying it's not a best practice to install a binary. I want to implement a hash checking to verify a binary is official.

**Comment by Azathothas** [comment]
Please see: https://github.com/metis-os/hysp-pkgs/blob/main/.github/scripts/pkg_metafetcher_x86_64.sh
Hash Checking & more is already implemented

**Comment by pwnwriter** [comment]
Used sha for this release, will implement blake3 in next release.
