### ISSUE TITLE
Suggestion for Improved User Feedback When No Packages are Installed in hysp

### ISSUE THREAD

**Issue by steinbrueckri** [pwnwriter/hysp#5]
Dear @pwnwriter,

First and foremost, I'd like to extend my heartfelt appreciation for your work on this fascinating project. It's been an exciting journey exploring what hysp has to offer.

I've recently encountered a minor issue that I believe could be improved for a better user experience. Upon initial use of hysp, specifically when running hysp list, I received an error message due to the absence of any installed packages. While the error makes sense given that no packages were installed, I propose a more user-friendly approach to this scenario.

Currently, the system responds with the following error:

```
$ hysp list
Info: Using default configuration.
────────────────────────────────
Error listing files in /home/steinbrueckri/.local/share/hysp/bin: No such file or directory (os error 2)

```

A more informative and less technical response could enhance the user's understanding of what needs to be done next. For instance, a message like "You have not installed any packages yet" would immediately clarify the situation without implying a system error.

This small change could significantly improve the user experience, especially for those who are new to hysp.

Thank you for considering this suggestion. I am looking forward to your thoughts and the continued evolution of this project.

Best regards,
Richard

**Comment by pwnwriter** [comment]
Hello @steinbrueckri ,

Thank you for your kind words and suggestions; I've made hysp to show messages as you recommended.

![screenshot_2023-11-27_18-23-59](https://github.com/pwnwriter/hysp/assets/90331517/01c20c63-6364-4af6-aa80-ebaf00e3e1d4)
